#!/usr/bin/env python3
"""
Web Publisher - GitHub Pages 自动发布工具
"""

import os
import yaml
import subprocess
import argparse
from datetime import datetime


def load_config(config_file):
    if os.path.exists(config_file):
        with open(config_file) as f:
            return yaml.safe_load(f)
    return None


def generate_html(title, description='', video_path='', output_dir='docs'):
    os.makedirs(output_dir, exist_ok=True)
    
    gen_time = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    video_info = ''
    
    if video_path and os.path.exists(video_path):
        size = os.path.getsize(video_path) / (1024 * 1024)
        video_info = f'''
        <div class="video-container">
            <video controls preload="metadata">
                <source src="{os.path.basename(video_path)}" type="video/mp4">
            </video>
            <p class="file-info">📁 {os.path.basename(video_path)} ({size:.2f} MB)</p>
        </div>'''
    
    html = f'''<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%);
            color: #eee;
            line-height: 1.6;
            min-height: 100vh;
        }}
        .container {{ max-width: 800px; margin: 0 auto; padding: 40px 20px; }}
        header {{
            text-align: center;
            padding: 60px 20px;
            background: linear-gradient(135deg, #646cff 0%, #7c3aed 100%);
            border-radius: 20px;
            margin-bottom: 40px;
        }}
        h1 {{ font-size: 2.5em; margin-bottom: 20px; }}
        section {{
            background: rgba(255,255,255,0.05);
            border-radius: 15px;
            padding: 30px;
            margin-bottom: 30px;
        }}
        h2 {{ color: #646cff; margin-bottom: 20px; }}
        video {{ max-width: 100%; border-radius: 10px; }}
        footer {{ text-align: center; padding: 40px; opacity: 0.7; }}
        @media (max-width: 600px) {{ h1 {{ font-size: 1.8em; }} }}
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>🎬 {title}</h1>
            <p>{description}</p>
        </header>
        <section>
            <h2>📋 项目说明</h2>
            <p>{description}</p>
        </section>
        {video_info}
        <footer>
            <p>🤖 Generated by OpenClaw Web Publisher</p>
            <p style="font-size:0.8em;opacity:0.5">{gen_time}</p>
        </footer>
    </div>
</body>
</html>'''
    
    path = os.path.join(output_dir, 'index.html')
    with open(path, 'w', encoding='utf-8') as f:
        f.write(html)
    print(f"✅ 已生成: {path}")


def commit_and_push(repo_path, message, branch='main', force=False):
    subprocess.run(['git', 'add', '.'], cwd=repo_path, check=True)
    result = subprocess.run(['git', 'status', '--porcelain'], cwd=repo_path, capture_output=True, text=True)
    if not result.stdout.strip():
        print("ℹ️  没有新变更")
        return
    subprocess.run(['git', 'commit', '-m', message], cwd=repo_path, check=True)
    args = ['git', 'push', '-u', 'origin', branch]
    if force: args.append('--force')
    subprocess.run(args, cwd=repo_path, check=True)
    print(f"✅ 已推送到 {branch}")


def main():
    parser = argparse.ArgumentParser(description='Web Publisher')
    parser.add_argument('--title', '-t', help='页面标题')
    parser.add_argument('--video', '-v', help='视频路径')
    parser.add_argument('--output', '-o', default='docs', help='输出目录')
    parser.add_argument('--description', '-d', help='描述')
    parser.add_argument('--config', '-c', help='配置文件')
    parser.add_argument('--push', action='store_true', help='推送')
    parser.add_argument('--message', '-m', help='提交信息')
    args = parser.parse_args()
    
    config = {}
    if args.config:
        config = load_config(args.config) or {}
    
    output = args.output or config.get('output_dir', 'docs')
    
    generate_html(
        title=args.title or config.get('title', 'Demo'),
        description=args.description or config.get('description', ''),
        video_path=args.video or config.get('video_path', ''),
        output_dir=output
    )
    
    if args.push or config.get('push'):
        commit_and_push(
            output,
            args.message or config.get('commit_message', 'docs: 更新'),
            config.get('github', {}).get('branch', 'main')
        )


if __name__ == '__main__':
    main()
